# require_relative "entity/msgpack/representation"
# require_relative "entity/msgpack/has_one_schema"
# require_relative "entity/msgpack/has_many_schema"
# require_relative "entity/msgpack/instant_schema"
# require_relative "entity/msgpack/attachment_schema"
# require_relative "entity/msgpack/date_schema"
# require_relative "entity/msgpack/geo_point_schema"